name: CI/CD Pipeline cho Laravel

on:
  push:
    branches:
      - main 
  workflow_dispatch:

jobs:
  # --- GIAI ĐOẠN 1: CHẠY TRÊN SERVER CỦA GITHUB ---
  build-and-push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Đăng nhập vào Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build và Push Image lên Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ductapdevops/datn-devops:latest 

  # --- GIAI ĐOẠN 2: CHẠY TRÊN SERVER UNBUTU ---
  deploy:
    name: Deploy to Ubuntu Server
    needs: build-and-push 
    runs-on: self-hosted   
    steps:
      - name: Fix permissions
        run: |
          sudo chown -R ductapdevops:ductapdevops ${{ github.workspace }} || true

      - name: Checkout code (Lấy file docker-compose.yml)
        uses: actions/checkout@v4
        with:
          clean: false
      - name: Dọn dẹp file rác nhưng giữ lại file cấu hình quan trọng
        run: |
          git clean -ffdx \
            -e .env \
            -e docker/mysql/data      
      - name: Triển khai ứng dụng (Pull & Run)
        run: |
          docker pull ductapdevops/datn-devops:latest
          
          docker compose down
          
          docker compose up -d
      - name: Tối ưu hóa Laravel và Migrations
        run: |
          docker exec laravel_app php artisan storage:link || true
          docker exec laravel_app php artisan optimize:clear
          docker exec laravel_app php artisan optimize